### PR TITLE
[ADD] Added OCA/Project modules

### PR DESCRIPTION
**Pull request by Trivedi-Vacha-SerpentCS**
- Added OCA/ Project Modules

### CODE REVIEW

**Comment by bvanjeelharia** [comment]
@Trivedi-Vacha-SerpentCS , you have not added the branch (15.0)

**Comment by Trivedi-Vacha-SerpentCS** [comment]
> @Trivedi-Vacha-SerpentCS , you have not added the branch (15.0)

@bvanjeelharia Can you please send the command to do so, What I have know it linked with latest commit.

**Comment by Trivedi-Vacha-SerpentCS** [comment]
> @Trivedi-Vacha-SerpentCS , you have not added the branch (15.0)

We have used command git submodule add -b 15.0 https://github.com/OCA/project.git project
in the terminal it is shwoing 15.0 branch only

**Comment by bvanjeelharia** [comment]
@Trivedi-Vacha-SerpentCS ,use this command- git submodule add -f -b 16.0 https://github.com/OCA/project.git project

**Comment by Trivedi-Vacha-SerpentCS** [comment]
> @Trivedi-Vacha-SerpentCS ,use this command- git submodule add -f -b 16.0 https://github.com/OCA/project.git project

This project is for 15.0 so we have to use 15.0 branch in the command, isn't it?

**Comment by bvanjeelharia** [comment]
Yes, that's correct it should be 15.0. My bad

**Comment by bvanjeelharia** [comment]
Also, @Trivedi-Vacha-SerpentCS , please take a fork of this repo on your github and then raise a PR from that henceforth

**Comment by Trivedi-Vacha-SerpentCS** [comment]
Closing the PR as will do from the Forked repo.

**Pull request closed without merging**
