### PR TITLE
[WIP][ADD]Added package.txt file

### PR DESCRIPTION
**Pull request by Trivedi-Vacha-SerpentCS**

### CODE REVIEW

**Comment by bvanjeelharia** [comment]
Please add modules in package.txt only once they are merged in the repo (and are available in the repo) and also update the paths of the modules (for ex.:third_party/project_scrum_agile should now be project_scrum_agile).Also, I have moved the module theme_onestein directly to the main folder instead of custom , so please update the package.txt file accordingly

**Comment by Trivedi-Vacha-SerpentCS** [comment]
> Please add modules in package.txt only once they are merged in the repo (and are available in the repo) and also update the paths of the modules (for ex.:third_party/project_scrum_agile should now be project_scrum_agile).Also, I have moved the module theme_onestein directly to the main folder instead of custom , so please update the package.txt file accordingly

I have moved this PR in WIP state, once all other modules pr merged, we will update this file accordingly

**Comment by bvanjeelharia** [comment]
web repo is not added as a submodule

**Comment by Trivedi-Vacha-SerpentCS** [comment]
> web repo is not added as a submodule

Added

**Pull request merged**
